export * from './advert-category.migrate'
export * from './advert-department.migrate'
export * from './advert-involvedparty.migrate'
export * from './advert-main-category.migrate'
export * from './advert-status.migrate'
export * from './advert-types.migrate'
export * from './advert.migrate'
