/* eslint-disable local-rules/disallow-kennitalas */
export type { Case } from '../../../lib/constants'

import { type Case } from '../../../lib/constants'

export const MOCK_DATA: Case[] = [
  {
    id: '1',
    date: '06.12.2025',
    type: 'Jafnréttisáætlun',
    company: 'Kallaklemma ehf.',
    companyAdmin: 'Jón Jónsson',
    companyAdminGender: 'Karl',
    kennitala: '470301-1234',
    email: 'jon@kallaklemma.is',
    isatCode: '62010',
    employeeCount: '45',
    status: 'Samþykkt',
    reviewer: 'Guðrún Einarsdóttir',
  },
  {
    id: '2',
    date: '06.12.2025',
    type: 'Jafnréttisáætlun',
    company: 'Blámi-hugbúnaður ehf.',
    companyAdmin: 'Anna Sigurðardóttir',
    companyAdminGender: 'Kona',
    kennitala: '470301-3920',
    email: 'anna@blami.is',
    isatCode: '62020',
    employeeCount: '30',
    status: 'Hafnað',
    reviewer: 'Sigurður Ólafsson',
  },
  {
    id: '3',
    date: '06.12.2025',
    type: 'Launagreining',
    company: 'Þrumuþursar ehf.',
    companyAdmin: 'Björn Björnsson',
    companyAdminGender: 'Karl',
    kennitala: '550301-2230',
    email: 'bjorn@thrumuthursar.is',
    isatCode: '46110',
    employeeCount: '120',
    status: 'Í vinnslu',
    reviewer: 'Anna Björnsdóttir',
  },
  {
    id: '4',
    date: '06.12.2025',
    type: 'Launagreining',
    company: 'Lúxuslúsin ehf.',
    companyAdmin: 'María Magnúsdóttir',
    companyAdminGender: 'Kona',
    kennitala: '640301-5540',
    email: 'maria@luxuslusin.is',
    isatCode: '47710',
    employeeCount: '22',
    status: 'Í vinnslu',
    reviewer: 'Kristján Magnússon',
  },
  {
    id: '5',
    date: '06.12.2025',
    type: 'Jafnréttisáætlun',
    company: 'Skvamp & Co.',
    companyAdmin: 'Ólafur Ólafsson',
    companyAdminGender: 'Karl',
    kennitala: '720301-4410',
    email: 'olafur@skvamp.is',
    isatCode: '74100',
    employeeCount: '18',
    status: 'Innsent',
    reviewer: '',
  },
  {
    id: '6',
    date: '06.12.2025',
    type: 'Launagreining',
    company: 'Vafrandi Vöfflur ehf.',
    companyAdmin: 'Sigríður Sigurbjörnsdóttir',
    companyAdminGender: 'Kona',
    kennitala: '800301-6670',
    email: 'sigridur@vafrandi.is',
    isatCode: '56100',
    employeeCount: '60',
    status: 'Innsent',
    reviewer: '',
  },
  {
    id: '7',
    date: '29.11.2025',
    type: 'Launagreining',
    company: 'Hringlóttur Hamingjubelgur ehf.',
    companyAdmin: 'Gunnar Gunnarsson',
    companyAdminGender: 'Karl',
    kennitala: '690301-7780',
    email: 'gunnar@hringlottur.is',
    isatCode: '85200',
    employeeCount: '200',
    status: 'Drög',
    reviewer: '',
  },
  {
    id: '8',
    date: '07.11.2025',
    type: 'Jafnréttisáætlun',
    company: 'Fagrsýn Labs ehf.',
    companyAdmin: 'Helga Helgadóttir',
    companyAdminGender: 'Kona',
    kennitala: '760301-8890',
    email: 'helga@fagrsyn.is',
    isatCode: '72190',
    employeeCount: '55',
    status: 'Í vinnslu',
    reviewer: 'Guðrún Einarsdóttir',
  },
]
