#!/bin/bash

SUBMODULE_PATH=submodules/monorepo
SPARSE_CHECKOUT_PATH="${SUBMODULE_PATH}/.git/info/sparse-checkout"
DESIRED_SPARSE_PATTERN="libs/shared/*"

# Ensure the submodule is initialized and updated.
git submodule update --init --recursive "${SUBMODULE_PATH}"

# Enable sparse-checkout if it's not already.
git -C "${SUBMODULE_PATH}" config core.sparseCheckout true

# Check and set the sparse-checkout configuration only if it's different.
if ! grep -Fxq "$DESIRED_SPARSE_PATTERN" "$SPARSE_CHECKOUT_PATH"; then
  echo "$DESIRED_SPARSE_PATTERN" >"$SPARSE_CHECKOUT_PATH"
  git -C "${SUBMODULE_PATH}" read-tree -mu HEAD
fi
