export enum LegalGazetteHTMLTemplates {
  COMMON = 'COMMON',
  RECALL_BANKRUPTCY = 'RECALL_BANKRUPTCY',
  RECALL_DECEASED = 'RECALL_DECEASED',
  DIVISION_MEETING_BANKRUPTCY = 'DIVISION_MEETING_BANKRUPTCY',
  DIVISION_MEETING_DECEASED = 'DIVISION_MEETING_DECEASED',
  DIVISION_ENDING_BANKRUPTCY = 'DIVISION_ENDING_BANKRUPTCY',
  DIVISION_ENDING_DECEASED = 'DIVISION_ENDING_DECEASED',
  FORECLOSURE = 'FORECLOSURE',
}
