import { type ColumnDef } from '@tanstack/react-table'

export const CATEGORY_SLUG_MAP: Record<string, string> = {
  jafnrettisaetlun: 'Jafnréttisáætlun',
  urbotaaaetlun: 'Úrbótaáætlun',
}

export type Case = {
  date: string
  category: string
  company: string
  ceo: string
  kennitala: string
  email: string
  isat: string
  ceoGender: string
  employees: number
}

export const MOCK_DATA: Case[] = [
  {
    date: '06.12.2025',
    category: 'Jafnréttisáætlun',
    company: 'Kallaklemma ehf.',
    ceo: 'Gunnar Gunnarsson',
    kennitala: '470301-1234',
    email: 'gunnar@kallaklemma.is',
    isat: '62010 Hugbúnaðargerð',
    ceoGender: 'Karl',
    employees: 32,
  },
  {
    date: '06.12.2025',
    category: 'Jafnréttisáætlun',
    company: 'Blámi-hugbúnaður ehf.',
    ceo: 'Jónína Jónsdóttir',
    kennitala: '470301-3920',
    email: 'postur@postur.is',
    isat: '62010 Hugbúnaðargerð',
    ceoGender: 'Kona',
    employees: 45,
  },
  {
    date: '06.12.2025',
    category: 'Úrbótaáætlun',
    company: 'Þrumuþursar ehf.',
    ceo: 'Sigríður Sigurðardóttir',
    kennitala: '550301-2230',
    email: 'sigrid@thrumu.is',
    isat: '45200 Viðgerð ökutækja',
    ceoGender: 'Kona',
    employees: 78,
  },
  {
    date: '06.12.2025',
    category: 'Úrbótaáætlun',
    company: 'Lúxuslúsin ehf.',
    ceo: 'Björn Björnsson',
    kennitala: '640301-5540',
    email: 'bjorn@luxus.is',
    isat: '47710 Verslun með fatnað',
    ceoGender: 'Karl',
    employees: 14,
  },
  {
    date: '06.12.2025',
    category: 'Jafnréttisáætlun',
    company: 'Skvamp & Co.',
    ceo: 'Helga Helgadóttir',
    kennitala: '720301-4410',
    email: 'helga@skvamp.is',
    isat: '73110 Auglýsingastarfsemi',
    ceoGender: 'Kona',
    employees: 22,
  },
  {
    date: '06.12.2025',
    category: 'Úrbótaáætlun',
    company: 'Vafrandi Vöfflur ehf.',
    ceo: 'Páll Pálsson',
    kennitala: '800301-6670',
    email: 'pall@vafrandi.is',
    isat: '56101 Veitingastaðir',
    ceoGender: 'Karl',
    employees: 9,
  },
  {
    date: '29.11.2025',
    category: 'Úrbótaáætlun',
    company: 'Hringlóttur Hamingjubelgur ehf.',
    ceo: 'Anna Sigríður Ólafsdóttir',
    kennitala: '690301-7780',
    email: 'anna@hringlottur.is',
    isat: '85200 Grunnskólakennsla',
    ceoGender: 'Kona',
    employees: 61,
  },
  {
    date: '07.11.2025',
    category: 'Jafnréttisáætlun',
    company: 'Fagrsýn Labs ehf.',
    ceo: 'Kristján Magnússon',
    kennitala: '760301-8890',
    email: 'kristjan@fagrsyn.is',
    isat: '72200 Rannsókna- og þróunarstarfsemi',
    ceoGender: 'Karl',
    employees: 37,
  },
  {
    date: '07.11.2025',
    category: 'Jafnréttisáætlun',
    company: 'Bragðaríka Bröltbúðin ehf.',
    ceo: 'Margrét Einarsdóttir',
    kennitala: '850301-9990',
    email: 'margret@brolt.is',
    isat: '10710 Brauðgerð',
    ceoGender: 'Kona',
    employees: 18,
  },
  {
    date: '15.10.2025',
    category: 'Jafnréttisáætlun',
    company: 'Norðurljós Digital ehf.',
    ceo: 'Eiríkur Eiríksson',
    kennitala: '590401-1120',
    email: 'eirikur@nordurljosdigital.is',
    isat: '62020 Ráðgjöf um tölvumál',
    ceoGender: 'Karl',
    employees: 54,
  },
  {
    date: '15.10.2025',
    category: 'Úrbótaáætlun',
    company: 'Gleðileg Grænmetisgarður ehf.',
    ceo: 'Ásta Rut Kristjánsdóttir',
    kennitala: '680501-3340',
    email: 'asta@graenmetisgarður.is',
    isat: '01130 Ræktun grænmetis',
    ceoGender: 'Kona',
    employees: 27,
  },
  {
    date: '02.10.2025',
    category: 'Jafnréttisáætlun',
    company: 'Stórviðri Verkfræðistofa hf.',
    ceo: 'Magnús Þórðarson',
    kennitala: '710601-4450',
    email: 'magnus@storvid.is',
    isat: '71121 Verkfræðiþjónusta',
    ceoGender: 'Karl',
    employees: 103,
  },
  {
    date: '02.10.2025',
    category: 'Úrbótaáætlun',
    company: 'Himinn og Höf ehf.',
    ceo: 'Ragnheiður Sigríðardóttir',
    kennitala: '010130-5561',
    email: 'ragnheidur@himinnhof.is',
    isat: '79110 Ferðaskrifstofa',
    ceoGender: 'Kona',
    employees: 41,
  },
  {
    date: '18.09.2025',
    category: 'Jafnréttisáætlun',
    company: 'Kaldakvísl Fjármál ehf.',
    ceo: 'Stefán Karlsson',
    kennitala: '630801-6670',
    email: 'stefan@kaldakvislfjarm.is',
    isat: '64190 Aðrar lánastofnanir',
    ceoGender: 'Karl',
    employees: 89,
  },
  {
    date: '18.09.2025',
    category: 'Úrbótaáætlun',
    company: 'Smáskrúfur Iðnaðarþjónusta ehf.',
    ceo: 'Þóra Benediktsdóttir',
    kennitala: '750901-7780',
    email: 'thora@smaskrufur.is',
    isat: '33120 Viðgerð véla',
    ceoGender: 'Kona',
    employees: 16,
  },
  {
    date: '04.09.2025',
    category: 'Jafnréttisáætlun',
    company: 'Breiðafjörður Sjávarafurðir hf.',
    ceo: 'Ólafur Guðmundsson',
    kennitala: '540301-8890',
    email: 'olafur@breidafjordur.is',
    isat: '10201 Fiskvinnsla',
    ceoGender: 'Karl',
    employees: 212,
  },
  {
    date: '04.09.2025',
    category: 'Úrbótaáætlun',
    company: 'Ljóssmiðjan ehf.',
    ceo: 'Katrín Halldórsdóttir',
    kennitala: '010130-9990',
    email: 'katrin@ljossmidjan.is',
    isat: '47540 Verslun með rafhlöður',
    ceoGender: 'Kona',
    employees: 33,
  },
]

export const COLUMNS: ColumnDef<Case>[] = [
  {
    accessorKey: 'date',
    header: 'Dagsetning',
    enableSorting: true,
  },
  {
    accessorKey: 'category',
    header: 'Flokkur',
    enableSorting: true,
  },
  {
    accessorKey: 'company',
    header: 'Fyrirtæki',
    enableSorting: true,
  },
]

export const DETAIL_FIELDS: Array<{ label: string; key: keyof Case }> = [
  { label: 'Fyrirtæki', key: 'company' },
  { label: 'Æðsti stjórnandi', key: 'ceo' },
  { label: 'Kennitala', key: 'kennitala' },
  { label: 'Netfang', key: 'email' },
  { label: 'ÍSAT atvinnugreinaflokkun', key: 'isat' },
  { label: 'Kyn æðsta stjórnanda', key: 'ceoGender' },
  { label: 'Fjöldi starfsmanna', key: 'employees' },
]
