/* eslint-disable local-rules/disallow-kennitalas */
export type { Case } from '../../../components/list-page/constants'

import { type Case } from '../../../components/list-page/constants'

export const MOCK_DATA: Case[] = [
  {
    id: '1',
    identifier: 'JA-2025-001',
    date: '06.12.2025',
    type: 'Jafnréttisáætlun',
    company: 'Kallaklemma ehf.',
    kennitala: '470301-1234',
    status: 'Samþykkt',
    reviewer: 'Guðrún Einarsdóttir',
    correctionDeadline: null,
    validUntil: '06.12.2026',
  },
  {
    id: '2',
    identifier: 'JA-2025-002',
    date: '06.12.2025',
    type: 'Jafnréttisáætlun',
    company: 'Blámi-hugbúnaður ehf.',
    kennitala: '470301-3920',
    status: 'Hafnað',
    reviewer: 'Sigurður Ólafsson',
    correctionDeadline: '06.03.2026',
    validUntil: null,
  },
  {
    id: '3',
    identifier: 'LA-2025-001',
    date: '06.12.2025',
    type: 'Launagreining',
    company: 'Þrumuþursar ehf.',
    kennitala: '550301-2230',
    status: 'Í vinnslu',
    reviewer: 'Anna Björnsdóttir',
    correctionDeadline: null,
    validUntil: null,
  },
  {
    id: '4',
    identifier: 'LA-2025-002',
    date: '06.12.2025',
    type: 'Launagreining',
    company: 'Lúxuslúsin ehf.',
    kennitala: '640301-5540',
    status: 'Í vinnslu',
    reviewer: 'Kristján Magnússon',
    correctionDeadline: null,
    validUntil: null,
  },
  {
    id: '5',
    identifier: 'JA-2025-003',
    date: '06.12.2025',
    type: 'Jafnréttisáætlun',
    company: 'Skvamp & Co.',
    kennitala: '720301-4410',
    status: 'Innsent',
    reviewer: '',
    correctionDeadline: null,
    validUntil: null,
  },
  {
    id: '6',
    identifier: 'LA-2025-003',
    date: '06.12.2025',
    type: 'Launagreining',
    company: 'Vafrandi Vöfflur ehf.',
    kennitala: '800301-6670',
    status: 'Innsent',
    reviewer: '',
    correctionDeadline: null,
    validUntil: null,
  },
  {
    id: '7',
    identifier: 'LA-2025-004',
    date: '29.11.2025',
    type: 'Launagreining',
    company: 'Hringlóttur Hamingjubelgur ehf.',
    kennitala: '690301-7780',
    status: 'Drög',
    reviewer: '',
    correctionDeadline: null,
    validUntil: null,
  },
  {
    id: '8',
    identifier: 'JA-2025-004',
    date: '07.11.2025',
    type: 'Jafnréttisáætlun',
    company: 'Fagrsýn Labs ehf.',
    kennitala: '760301-8890',
    status: 'Í vinnslu',
    reviewer: 'Guðrún Einarsdóttir',
    correctionDeadline: null,
    validUntil: null,
  },
]
