export const frontPageText = {
  heroTitle: 'Ritstjórn Jafnréttisstofu',
  heroImageAlt: 'Ritstjórn Jafnréttisstofu',
  heroDescription:
    'Hér má finna jafnréttisáætlanir og skýrslur um kynjabundinn launamun, ásamt úrbótaáætlunum.',
  heildarlisti: {
    description:
      'Yfirlit yfir innsendingar sem eru óúthlutaðar og ekki í vinnslu',
    title: 'Innsendingar',
    href: '/yfirlit',
  },
  jafnrettisaetlanir: {
    description: 'Yfirlit jafnréttisáætlana og meðferð þeirra.',
  },
  urbotaaetlanir: {
    description: 'Yfirlit úrbótaáætlana og meðferð þeirra.',
  },
  sectionTitle: 'Staða mála',
  tabGeneral: 'Almennt',
  tabMine: 'Mín mál',
  statsTitle: 'Tölfræði',
  statsWindows: {
    last30: 'Síðustu 30 dagar',
    thisYear: 'Þetta ár',
    allTime: 'Allt saman',
  },
  statsIntros: {
    last30: 'Hlutfall mála eftir stöðu síðustu 30 daga.',
    thisYear: 'Hlutfall mála eftir stöðu á þessu ári.',
    allTime: 'Hlutfall mála eftir stöðu frá upphafi.',
  },
  panelStats: {
    title: 'Tölulegar upplýsingar',
    description:
      'Upplýsingar birtar opinberlega á vef jafnréttisstofu og fylgst er með árangri ...',
    linkText: 'Lesa meira',
  },
  panelExport: {
    title: 'Keyra út lista',
    description:
      'Sækja skýrslur og tölfræðileg gögn um starfsemi stofnunarinnar.',
    linkText: 'Sækja skýrslu',
  },
}

export const overviewText = {
  heroTitle: 'Vinnslusvæði',
  heroDescription:
    'Hér má finna yfirlit yfir allar innsendar jafnréttisáætlanir og skýrslur um kynjabundinn launamun, ásamt úrbótaáætlunum.',
  imageAlt: 'Innsendingar',
  breadcrumbOverview: 'Yfirlit',
  tabInnsendingar: 'Innsendingar',
  tabInProgress: 'Í vinnslu',
  tabAfgreitt: 'Afgreitt',
  resultsText: 'færslur fundust',
  noComments: 'Engar athugasemdir',
  waitingForAction: 'Beðið svara',
  openAdmin: 'Opna ritjstjórn',
  filter: {
    heading: 'Leit og síun',
    placeholder: 'Sláðu inn leitarorð',
    categoryLabel: 'Flokkur',
    reviewerLabel: 'Starfsmaður',
    dateLabel: 'Dagsetning',
    typeLabel: 'Tegund',
    companyLabel: 'Fyrirtæki',
    dateRangeLabel: 'Tímabil',
    dateFrom: 'Frá',
    dateFromPlaceholder: 'Veldu dagsetningu',
    dateTo: 'Til',
    dateToPlaceholder: 'Veldu dagsetningu',
    clearDates: 'Hreinsa dagsetningar',
  },
  createEqualityReport: {
    drawerLabel: 'Skrá jafnréttisáætlun',
    buttonLabel: 'Jafnréttisáætlun',
    heading: 'Ný jafnréttisáætlun',
    successToast: 'Skýrsla send inn',
  },
  createSalaryReport: {
    drawerLabel: 'Skrá launagreiningu',
    buttonLabel: 'Skýrslugjöf',
    heading: 'Ný launagreining',
    excelHeading: 'Excel innflutningur',
    excelPlaceholder: 'Veldu Excel skrá til að flytja inn launagreiningargögn',
    switchFile: 'Skipta um skrá',
    chooseFile: 'Velja skrá',
    deviationsHeading: 'Frávik',
    deferLabel: 'Fresta skilum frávika',
    deferReasonLabel: 'Ástæða frestunar',
    employeeCountHeading: 'Starfsmannafjöldi',
    excelSuccessToast: 'Excel skrá flutt inn',
    excelErrorToast: 'Villa við innflutning á Excel skrá',
    successToast: 'Skýrslugjöf send inn',
  },
}

export const reportText = {
  heroTitle: 'Vinnslusvæði',
  heroDescription:
    'Forem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.',
  breadcrumbOverview: 'Yfirlit',
  sidebarTitle: 'Upplýsingar',
  tabEquality: 'Jafnréttisáætlun',
  tabCompany: 'Fyrirtækið',
  tabSalary: 'Skýrslugjöf',
  tabsLabel: 'Skýrsla',
  stepApproved: 'Afgreitt',
  comments: {
    heading: 'Athugasemdir',
    label: 'Athugasemd',
    placeholder: 'Bættu við athugasemd',
    sendToApplicant: 'Senda á innsendanda',
    submit: 'Vista athugasemd',
    visibleToApplicant: 'Sýnileg innsendanda',
    seeAllComments: 'Sjá allar athugasemdir',
    createError: 'Villa við að vista athugasemd',
    deleteError: 'Villa við að eyða athugasemd',
    deleteSuccess: 'Athugasemd eytt',
  },
  statusSelect: {
    successToast: 'Uppfærsla á stöðu tókst.',
    errorToast: 'Villa við að uppfæra stöðu. Vinsamlegast reyndu aftur síðar.',
    assignButton: 'Færa í vinnslu',
    approveButton: 'Samþykkja',
    denyButton: 'Hafna',
  },
  employeeSelect: {
    label: 'Starfsmaður',
    successToast: 'Úthlutun tókst.',
    errorToast: 'Villa við að úthluta starfsmanni.',
  },
  detailFields: {
    isatCode: 'ÍSAT atvinnugreinaflokkun',
    companyAdminGender: 'Kyn æðsta stjórnanda',
    employeeCount: 'Fjöldi starfsmanna',
    address: 'Heimilisfang',
    city: 'Sveitarfélag',
    province: 'Landshluti',
    fines: 'Dagsektir',
  },
  companyTab: {
    companyInfoHeading: 'Upplýsingar fyrirtækis',
    averageEmployeesHeading: 'Meðalfjöldi starfsmanna',
    genderNeutralRegistry: 'Hlutlaus skráning kyns í Þjóðskrá',
    subsidaries: 'Dótturfélög',
  },
  denialModal: {
    heading: 'Höfnun skýrslu',
    description:
      'Vinsamlegast gerðu grein fyrir ástæðu höfnunar. Athugið að afrit af þessum texta er sent til innsendanda.',
    warningTitle: 'Athugið',
    warningMessage: 'Þessi aðgerð er óaftukræf og mun vísa skýrslunni frá.',
    reasonLabel: 'Ástæða höfnunar',
    submitButton: 'Vista',
  },
  equalityTab: {
    emptyTitle: 'Engin jafnréttisáætlun',
    emptyMessage:
      'Engin jafnréttisáætlun fannst fyrir þessa skýrslu. Vinsamlegast hafðu samband við fyrirtækið til að fá frekari upplýsingar.',
    approvedDateLabel: 'Dagsetning samþykktar',
    expiryLabel: 'Gildistími',
    responsibleLabel: 'Ábyrgðaraðili',
  },
  salaryTab: {
    emptyTitle: 'Engin skýrslugjöf ',
    emptyMessage:
      'Engin skýrslugjöf fannst. Vinsamlegast hafðu samband við fyrirtækið til að fá frekari upplýsingar.',
    outliersPostponedTitle: 'Frestur á úrbótaáætlun.',
    outliersPostponedMessage:
      'Fyrirtækið hefur óskað eftir fresti við skil á úrbótaáætlun.',
    wageGapDescription: 'Óleiðréttur launamunur milli karla og kvenna',
    avgSalaryMale: 'Meðallaun karla',
    avgSalaryFemale: 'Meðallaun kvenna',
    wageGapLabel: 'Launamunur',
    noDataMessage: 'Engin launagögn til að birta',
    chartTitle: 'Stig á móti meðallaunum',
    chartDescription:
      'Hér má sjá línulega affallsgreiningu á uppreiknuðum launum á milli kynja.',
    chartScaleScore: 'stig',
    chartScaleCurrency: 'kr.',
    chartTooltipScore: 'Stig',
    chartTooltipSalary: 'Laun',
    seriesNeutral: 'Hlutlaust',
    seriesAvgSalary: 'Meðallaun',
    outlierTable: {
      employee: 'Starfsmaður',
      heading: 'Úrbótaáætlun',
      numberHeader: 'Númer',
      roleHeader: 'Starf',
      genderHeader: 'Kyn',
      deviationHeader: 'Launafrávik',
      groupHeader: 'Hópur',
      groupLabel: 'Hópur',
      reasonLabel: 'Ástæða',
      actionLabel: 'Aðgerð',
      signatureNameLabel: 'Nafn undirritanda',
      signatureRoleLabel: 'Hlutverk undirritanda',
      points: 'Stig',
      salary: 'Laun',
    },
    remedyDeadlineLabel: 'Frestur til úrbóta',
    remedyDeadlinePlaceholder: 'Valin dagsetning fyrir úrbótafrest',
  },
  timeline: {
    today: 'Í dag',
    yesterday: 'Í gær',
    company: 'Fyrirtæki',
    employee: 'Starfsmaður',
    reportSubmitted: 'Skýrsla innsend',
    assigned: 'Úthlutað',
    unassigned: 'tekur sig af málinu',
    superseded: 'Útrunnið',
    registersMessage: 'skráir skilaboð',
    submitsReport: 'sendir inn skýrslu',
    claimsCase: 'merkir sér málið',
    assignedOther: 'merkti',
    assignedOtherSuffix: 'á málið',
    unassignedOther: 'tók',
    unassignedOtherSuffix: 'af málinu',
    movesToStatus: 'færir mál í stöðuna:',
  },
  salaryStatsLoadError: 'Villa við að hlaða tölfræðigögn fyrir skýrslu',
  salaryStatsLoadErrorMessage:
    'Vinsamlegast reyndu aftur síðar eða hafðu samband við kerfisstjóra ef vandamálið heldur áfram.',
  loadError: 'Villa kom upp við að hlaða skýrslu',
  loadSidebarError: 'Villa kom upp við að hlaða hliðarstiku',
}

export const companiesText = {
  heading: 'Fyrirtæki',
  heroDescription:
    'Hér eru skráð fyrirtæki í kerfinu. Hægt er að leita að fyrirtækjum, sía eftir stærð og skoða stöðu jafnréttismála.',
  newButton: 'Nýtt fyrirtæki',
  filterHeading: 'Leit og síun',
  filterPlaceholder: 'Sláðu inn leitarorð',
  avgEmployeeCount: 'Meðalfjöldi starfsmanna',
  validPeriod: 'Gildistími',
  dailyFines: 'Dagsektir',
  overdue: 'Skiladagur',
  overdueTag: 'Skiladagur liðinn',
  quarantine: 'Sóttkví',
  location: 'Staður',
  region: 'Landshluti',
  regionPlaceholder: 'Veldu landshluta',
  postcode: 'Póstnúmer',
  postcodePlaceholder: 'Veldu póstnúmer',
  filterNoResults: 'Ekkert fannst',
  isatCategory: 'ÍSAT-flokkur',
  isatCategoryPlaceholder: 'Leita að ÍSAT-flokki',
  isatCategoryNoResults: 'Engir flokkar fundust',
  resultsText: 'fyrirtæki fundust',
  noData: 'Engin fyrirtæki skráð',
  expandedRow: {
    salaryRequired: 'Skýrslugjöf skylda',
    equalityRequired: 'Jafnréttisáætlun skylda',
    validUntilPrefix: 'Gildir til:',
    avgEmployees: 'Meðalfjöldi starfsmanna',
    contactPerson: 'Tengiliður',
    contactEmail: 'Netfang tengiliðar',
    viewReport: 'Opna skýrslu',
    equalityDueAt: 'Næsti skiladagur jafnréttisáætlunar',
    salaryDueAt: 'Næsti skiladagur launagreiningar',
  },
  createModal: {
    title: 'Skrá nýtt fyrirtæki',
    kennitalaEyebrow: 'Kennitala fyrirtækis',
    kennitalaPlaceholder: '000000-0000',
    lookupButton: 'Fletta upp',
    notFoundError: 'Fyrirtæki fannst ekki í þjóðskrá',
    nameLabel: 'Nafn fyrirtækis',
    employeeCountLabel: 'Meðalfjöldi starfsmanna',
    submit: 'Skrá fyrirtæki',
    successToast: 'Fyrirtæki skráð',
    errorToast: 'Villa við skráningu fyrirtækis',
  },
  importModal: {
    title: 'Flytja inn fyrirtækjaskrá',
    description:
      'Veldu Excel-skrá (.xlsx) með árlegri fyrirtækjaskrá. Skráin er staðreyndaruppspretta — fyrirtæki eru stofnuð, uppfærð eða merkt óþekkt eftir innihaldi hennar.',
    button: 'Flytja inn skrá',
    chooseFile: 'Velja skrá',
    reading: 'Les skrá…',
    yearLabel: 'Tekjuár',
    noChanges: 'Engar breytingar fundust í skránni.',
    noticeCount: 'athugasemd(ir)',
    confirm: 'Staðfesta innflutning',
    cancel: 'Hætta við',
    close: 'Loka',
    chooseAnother: 'Velja aðra skrá',
    successToast: 'Innflutningur staðfestur',
    errorToast: 'Villa við innflutning',
    committedBanner: 'Innflutningur staðfestur',
    sections: {
      created: 'Ný fyrirtæki',
      updated: 'Uppfærð',
      reactivated: 'Endurvirkjuð',
      deactivated: 'Óvirkjuð (vantar í skrá)',
      unchanged: 'Óbreytt',
      invalid: 'Ógildar línur',
    },
    rowPrefix: 'Lína',
  },
  detailView: {
    heading: 'Upplýsingar um fyrirtæki',
    tabInfo: 'Upplýsingar',
    tabReports: 'Skýrslur',
    tabsLabel: 'Fyrirtækjaflippar',
    timelineHeading: 'Saga fyrirtækis',
    sidebarTitle: 'Staða fyrirtækis',
    statusLabel: 'Staða',
    finesButton: 'Hefja dagsektir',
    noReports: 'Engar skýrslur skráðar',
    reportsLoadError: 'Villa við að hlaða skýrslur',
    noCompany: 'Fyrirtæki fannst ekki',
    comments: {
      label: 'Athugasemdir',
      placeholder: 'Bættu við athugasemd',
      submit: 'Vista athugasemd',
    },
  },
}

export const usersText = {
  heroTitle: 'Notendur',
  heroDescription:
    'Hér eru skráðir notendur kerfisins. Hægt er að bæta við nýjum notendum, breyta upplýsingum eða óvirkja notendur.',
  createButton: 'Nýr notandi',
  showInactive: 'Sýna óvirka',
  hideInactive: 'Fela óvirka',
  resultsText: 'notendur fundust',
  noData: 'Engir notendur skráðir',
  active: 'Virkur',
  inactive: 'Óvirkur',
  actionsHeading: 'Aðgerðir',
  roleLabel: 'Hlutverk',
  roleAdmin: 'Stjórnandi',
  roleEditor: 'Ritstjórn',
  modal: {
    createTitle: 'Nýr notandi',
    editTitle: 'Breyta notanda',
    nationalIdLabel: 'Kennitala',
    firstNameLabel: 'Fornafn',
    lastNameLabel: 'Eftirnafn',
    roleLabel: 'Hlutverk',
    roleAdmin: 'Stjórnandi',
    roleEditor: 'Ritstjórn',
    statusEyebrow: 'Staða notanda',
    activeLabel: 'Virkur notandi',
    create: 'Stofna notanda',
    save: 'Vista breytingar',
    createSuccess: 'Notandi stofnaður',
    saveSuccess: 'Breytingar vistaðar',
    createError: 'Villa við stofnun notanda',
    userAlreadyExists:
      'Notandi með þessari kennitölu er þegar til. Athugaðu hvort hann geti verið í listanum yfir óvirka notendur.',
    saveError: 'Villa við vistun breytinga',
  },
}

export const loginText = {
  heading: 'Innskráning',
  description:
    'Skráðu þig inn í kerfi Jafnréttisstofu með rafrænum skilríkjum.',
  submitButton: 'Skrá inn með rafrænum skilríkjum',
  errorTitle: 'Innskráning mistókst',
  errorMessage: 'Ekki tókst að skrá þig inn. Reyndu aftur síðar.',
}

export const errorPageText = {
  heading: 'Villa við innskráningu',
  accessDenied: 'Þú hefur ekki aðgang að þessu kerfi.',
  defaultError:
    'Eitthvað fór úrskeiðis við innskráningu. Vinsamlegast reyndu aftur.',
}

export const notFoundText = {
  title: 'Síða fannst ekki',
  message:
    'Ekkert fannst á þessari slóð. Mögulega hefur síðan verið fjarlægð eða færð til.',
}

export const reportNotFoundText = {
  title: 'Skýrsla fannst ekki',
  message:
    'Engin skýrsla fannst með þetta auðkenni. Mögulega hefur hún verið fjarlægð eða auðkennið er rangt.',
  backToOverview: 'Til baka í yfirlit',
}

export const serverErrorText = {
  title: 'Eitthvað fór úrskeiðis',
  message:
    'Villa kom upp við að sækja gögn. Vinsamlegast reyndu aftur síðar eða hafðu samband við kerfisstjóra ef vandinn líður áfram.',
  tryAgain: 'Reyna aftur',
  backToOverview: 'Til baka í yfirlit',
}

export const headerText = {
  logoAlt: 'Jafnréttisstofa logo',
  brand: 'Jafnréttisstofa',
  controlPanelTitle: 'Stjórnborð',
  userMenuLabel: 'Notandi',
  logout: 'Útskrá',
  logoutButton: 'Skrá út',
}

export const sharedText = {
  breadcrumbHome: 'Forsíða',
  admin: 'Ritstjórn',
  unknown: 'Óþekkt',
  yesLabel: 'Já',
  noLabel: 'Nei',
  statusLabel: 'Staða',
  delete: 'Eyða',
  companies: 'Fyrirtæki',
  filter: {
    labelClearAll: 'Hreinsa allar síur',
    labelOpen: 'Opna síur',
    labelClose: 'Loka síum',
    labelClear: 'Hreinsa',
    labelTitle: 'Síur',
    labelResult: 'Sýna niðurstöður',
  },
  statusLabels: {
    DRAFT: 'Drög',
    SUBMITTED: 'Innsent',
    IN_REVIEW: 'Í vinnslu',
    APPROVED: 'Samþykkt',
    DENIED: 'Hafnað',
    SUPERSEDED: 'Útrunnið',
    POSTPONED: 'Frestað',
    WITHDRAWN: 'Dregin til baka',
  },
  typeLabels: {
    EQUALITY: 'Jafnréttisáætlun',
    SALARY: 'Skýrslugjöf',
    IMPROVEMENT_PLAN: 'Úrbótaáætlun',
  },
  genders: {
    male: 'Karl',
    female: 'Kona',
    neutral: 'Kynhlutlægt',
    maleCount: 'Karlar',
    femaleCount: 'Konur',
  },
  form: {
    nameLabel: 'Nafn',
    kennitalaLabel: 'Kennitala',
    emailLabel: 'Netfang',
    phoneLabel: 'Símanúmer',
    phoneShortLabel: 'Sími',
    genderLabel: 'Kyn',
    companyHeading: 'Fyrirtæki',
    companySelect: 'Veldu fyrirtæki',
    topManagerHeading: 'Æðsti stjórnandi',
    contactHeading: 'Tengiliður',
    reset: 'Hreinsa',
    submit: 'Senda inn',
    cancel: 'Hætta við',
    save: 'Vista',
    errorToast: 'Villa við innsendingu',
  },
  empty: {
    title: 'Ekkert fannst',
    message:
      'Engin gögn fundust. Vinsamlegast hafðu samband við fyrirtækið til að fá frekari upplýsingar.',
  },
  files: 'Skjöl',
}
