version: '3'

services:
  db_official_journal_api:
    image: public.ecr.aws/docker/library/postgres:16
    container_name: db_official_journal_api
    environment:
      - POSTGRES_DB=dev_db_official_journal
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - '5433:5432'
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local