version: '3'

services:
  db_official_journal:
    image: public.ecr.aws/docker/library/postgres:16
    container_name: db_official_journal
    environment:
      - POSTGRES_DB=dev_db_official_journal
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - 5432:5432
