name: '✋ Manual Release'
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  id-token: write
  contents: write

jobs:
  quality-checks:
    name: ✅ Quality checks
    uses: './.github/workflows/quality.yml'

  manual-release:
    needs: quality-checks
    uses: 'aproorg/github-workflows/.github/workflows/manual-release.yml@main'
    secrets:
      token: ${{ secrets.DMR_ACCOUNT_PAT  }}
